# Generated by Django 3.1.4 on 2021-01-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='parents',
            new_name='parent',
        ),
    ]
